apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/mscairlinestickets/booking-service/k8s?ref=main

patchesStrategicMerge:

configMapGenerator:
  - behavior: merge
    name: booking-config

images:
  - name: booking-service
    newName: 234559571647.dkr.ecr.us-east-1.amazonaws.com/booking-service
    newTag: latest

replicas:
  - name: booking-service
    count: 2