apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/mscairlinestickets/booking-service/k8s?ref=main
  - booking-hpa.yaml

patchesStrategicMerge:
  - patch-env.yaml
  - patch-resources.yaml
  - patch-volumes.yaml
  - patch-tracing.yaml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yaml
    name: booking-config

images:
  - name: booking-service
    newName: 234559571647.dkr.ecr.us-east-1.amazonaws.com/msc/booking-service
    newTag: latest