apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  template:
    spec:
      containers:
        - name: booking-service
          volumeMounts:
            - name: postgres-credentials-volume
              mountPath: /workspace/secrets/postgres
            - name: oauth2-resourceserver-secret-volume
              mountPath: /workspace/secrets/oauth2-resourceserver
      volumes:
        - name: postgres-credentials-volume
          secret:
            secretName: postgres-booking-credentials
        - name: oauth2-resourceserver-secret-volume
          secret:
            secretName: oauth-resourceserver-secret