apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  template:
    spec:
      containers:
        - name: booking-service
          resources:
            requests:
              memory: "756Mi"
              cpu: "100m"
           