apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msc-airlines
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mscairlinestickets/airline-deployment
    targetRevision: HEAD
    path: kubernetes/applications/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: default