apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
        - name: auth-service
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.33.3.jar"
            - name: OTEL_SERVICE_NAME
              value: auth-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo:4317
            - name: OTEL_METRICS_EXPORTER
              value: none