apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/mscairlinestickets/ticket-service/k8s?ref=main

patchesStrategicMerge:
  - patch-env.yaml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yaml
    name: ticket-config

images:
  - name: ticket-service
    newName: 234559571647.dkr.ecr.us-east-1.amazonaws.com/ticket-service
    newTag: no-security

replicas:
  - name: ticket-service
    count: 2