apiVersion: argoproj.io/v1alpha1
metadata:
  name: msc-airlines-database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mscairlinestickets/airline-deployment
    targetRevision: HEAD
    path: kubernetes/platform/development/services/airline-postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
