apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
spec:
  template:
    spec:
      containers:
        - name: edge-service
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "200"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            